Visor glasses and eye piece varients
34th-Para-Recon-Brimstone-Company/34th-PRC-Aux-Mod pull request #228
Opened 2024-11-12 11:35 UTC by Snamberr

5 colors for the eye piece and visor glasses on the marine helmet.

2024-11-12 15:06 UTC, Lupus590 requested changes
color is a little too generic

2024-11-12 15:06 UTC, Lupus590 commented on src/Addons/34thPRC_AceArsenalExtended/config.cpp
> +			options[] = {"camo", "eyewear", "medic", "color"};
```suggestion
			options[] = {"camo", "eyewear", "medic", "eyewear_color"};

```

2024-11-12 15:06 UTC, Lupus590 commented on src/Addons/34thPRC_AceArsenalExtended/config.cpp
> +			class color
```suggestion
			class eyewear_color

```

2024-11-12 15:06 UTC, Lupus590 commented on src/Addons/34thPRC_AceArsenalExtended/config.cpp
> +			color = "green"
```suggestion
			eyewear_color = "green"

```

2024-11-13 10:15 UTC, Lupus590 commented
Can you update the changelog too?

2024-11-13 10:22 UTC, Snamberr commented
sure, do I put the changes in Unreleased or do i make a 0.17.0 in the changelog?

2024-11-13 10:45 UTC, Lupus590 commented
Colour bleed on tropic purple non-medic eyepeice
![image](https://github.com/user-attachments/assets/ff479d9b-530c-4b04-b479-f643b396d7d7)

Otherwise it looks good

2024-11-13 11:22 UTC, Snamberr commented
noticed another issue, gonna fix it

2024-11-13 11:28 UTC, Snamberr commented
I don't see anymore issues in game.

2024-11-13 11:58 UTC, Lupus590 approved these changes

2024-11-13 11:59 UTC, merged