custom armor
34th-Para-Recon-Brimstone-Company/34th-PRC-Aux-Mod pull request #236
Opened 2024-11-21 17:41 UTC by OverYandere

The new MA ODST armor has been implemented. Includes: CH252D Helmet in 5 camo variants with 3 visor colors, M52 Vest in 5 camo patterns with toggle-able medic sigil for standard shoulders as well as CQB and Marksman option for all 5 camos, shoulder-less marine uniform to go with the new armor included in 6 camo patterns.

Custom Armor framework coming in the next batch.

2024-11-22 19:14 UTC, Lupus590 commented
It looks great however there is some issues with shoulders, check your file paths for textures. Also, I still need to look at the code.
![image](https://github.com/user-attachments/assets/6155af23-f4f4-4586-be11-8ec6b4020876)
![image](https://github.com/user-attachments/assets/c6b56c6a-360e-4dc5-897b-65ddc7e13954)

2024-11-23 17:52 UTC, Lupus590 commented
Misriah armoury updated and I think it affects this pull request.

2024-11-23 18:08 UTC, Lupus590 commented
Also, can the new ODST stuff go in a new folder `odst2`?

2024-11-23 18:27 UTC, Lupus590 commented
Also, can we split the custom armour and the new ODST stuff into separate pull request?

2024-11-25 21:50 UTC, Lupus590 commented
blocked by #230

2024-12-01 00:03 UTC, Lupus590 requested changes

2024-12-01 00:11 UTC, OverYandere commented on src/Addons/34thPRC_ArmourCustom/config.cpp
> +			//"MA_Armor", //MA_Armor
I forgot to take it out during attempts to get depolarized working on ArmourCustom. There was an issue with ItemInfo not being defined despite inheriting from ArmourStandard where it works so I tried to go 1 up and inherit from MA_Armor which also didn't work. I ended up having to do class ItemInfo; in the main cfg and that worked.

2024-12-01 00:21 UTC, Lupus590 commented on src/Addons/34thPRC_ArmourCustom/config.cpp
> +			//"MA_Armor", //MA_Armor
```suggestion

```

2024-12-01 02:42 UTC, OverYandere commented on src/Addons/34thPRC_ArmourCustom/config.cpp
> +			//"MA_Armor", //MA_Armor
Deleted in coming patch

2024-12-01 02:43 UTC, OverYandere commented on src/Addons/34thPRC_ArmourCustom/data/odst2/config_weapons.hpp
> +//Include each player's config
Done in next commit

2024-12-01 02:43 UTC, OverYandere commented on src/Addons/34thPRC_ArmourCustom/data/marines2/config_weapons.hpp
> +//Put player includes here
Done in next commit

2024-12-01 02:44 UTC, OverYandere commented on src/Addons/34thPRC_AceArsenalExtended/data/aax_models/weapons/armour_standard/marines2/config.hpp
> +		alwaysSelectable = 1;
Done in next commit

2024-12-01 02:44 UTC, OverYandere commented on src/Addons/34thPRC_AceArsenalExtended/data/aax_models/weapons/armour_standard/marines2/config.hpp
> +	class camo
Done in next commit

2024-12-01 03:09 UTC, OverYandere commented on src/changelog.md
> -- 5 color variants for the marine helmet eyewear
Should be reverted now

2024-12-01 03:18 UTC, Lupus590 approved these changes

2024-12-21 11:57 UTC, Lupus590 commented on .gitattributes
> +* -text
We might be able to remove this

2024-12-23 22:54 UTC, Lupus590 commented on .gitattributes
> +* -text
```suggestion

```

2024-12-23 23:05 UTC, Lupus590 approved these changes

2024-12-25 15:55 UTC, Lupus590 approved these changes

2024-12-25 16:50 UTC, merged