Feature/custom armour cappy
34th-Para-Recon-Brimstone-Company/34th-PRC-Aux-Mod pull request #277
Opened 2024-12-27 20:01 UTC by OverYandere

Branch includes Cappy's new requested vest. I am planning on implementing the helmet as part of separate branches.

2024-12-27 20:11 UTC, Lupus590 requested changes
Can't check everything on my phone but this is what I spotted.

We need to fix this whitespace issue, it is making PRs a pain to review.

2024-12-27 20:11 UTC, Lupus590 commented on .gitignore
> +build.ps1
Please revert this.

2024-12-27 20:13 UTC, OverYandere commented on .gitignore
> +build.ps1
removed

2024-12-28 14:20 UTC, Lupus590 reviewed
No medic versions?

2024-12-28 15:57 UTC, Lupus590 approved these changes

2024-12-28 16:07 UTC, merged